version: "3"

services:
  blockchain_drf:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./blockchain_drf:/blockchain_drf
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

